/*******************************************************************************
 * Pattern builder for pattern secmer.core.referenceModel
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.compiled.emf.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.secmer.core;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.compiled.emf.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.compiled.emf.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern secmer.core.referenceModel
 */
public class PatternBuilderForreferenceModel implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("secmer.core.referenceModel".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("secmer.core.referenceModel");
		
		final Address<? extends Receiver> var_290 = buildable.patternCollector("secmer.core.referenceModel");
		final Stub<Address<? extends Supplier>> var_291 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_292 = ((EClass) (EPackage.Registry.INSTANCE.getEPackage("http://securechange.eu/secmer/tool").getEClassifier("SecMERIntegrationModel"))).getEStructuralFeature("referenceModels");
		final Stub<Address<? extends Supplier>> var_293 = buildable.binaryEdgeTypeStub(new FlatTuple(new Object[] {"SecMERIntegrationModel", "ReferenceModel"}), var_292);
		final TupleMask var_294 = new TupleMask(new int[] {}, 0);
		final TupleMask var_295 = new TupleMask(new int[] {}, 2);
		final TupleMask var_296 = new TupleMask(new int[] {0, 1}, 2);
		final Stub<Address<? extends Supplier>> var_297 = buildable.buildBetaNode(var_291, var_293, var_294, var_295, var_296, false);
		final Stub<Address<? extends Supplier>> var_298 = buildable.buildInjectivityChecker(var_297, 1, new int[] {0});
		final TupleMask var_299 = new TupleMask(new int[] {0, 1}, 2);
		final Stub<Address<? extends Supplier>> var_300 = buildable.buildTrimmer(var_298, var_299);
		buildable.buildConnection(var_300, var_290);
		return var_290;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("secmer.core.referenceModel".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("SecMERIntegrationModel", 0);
			posMapping.put("ReferenceModel", 1);

		}
		return posMapping;
	}
}
