/*******************************************************************************
 * Pattern builder for pattern secmer.sistar.transform.actorDelFromTropos
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.compiled.emf.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.secmer.sistar.transform;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.compiled.emf.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.compiled.emf.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern secmer.sistar.transform.actorDelFromTropos
 */
public class PatternBuilderForactorDelFromTropos implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("secmer.sistar.transform.actorDelFromTropos".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("secmer.sistar.transform.actorDelFromTropos");
		
		final Address<? extends Receiver> var_133 = buildable.patternCollector("secmer.sistar.transform.actorDelFromTropos");
		final Stub<Address<? extends Supplier>> var_134 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Stub<Address<? extends Supplier>> var_135 = buildable.patternCallStub(new FlatTuple(new Object[] {"Actor", "Link"}), "secmer.sistar.transform.actorMappingToTropos");
		final TupleMask var_136 = new TupleMask(new int[] {}, 0);
		final TupleMask var_137 = new TupleMask(new int[] {}, 2);
		final TupleMask var_138 = new TupleMask(new int[] {0, 1}, 2);
		final Stub<Address<? extends Supplier>> var_139 = buildable.buildBetaNode(var_134, var_135, var_136, var_137, var_138, false);
		final Stub<Address<? extends Supplier>> var_140 = buildable.patternCallStub(new FlatTuple(new Object[] {"Link", "TroposActor"}), "secmer.sistar.transform.actorMappingFromTropos");
		final TupleMask var_141 = new TupleMask(new int[] {1}, 2);
		final TupleMask var_142 = new TupleMask(new int[] {0}, 2);
		final TupleMask var_143 = new TupleMask(new int[] {}, 2);
		final Stub<Address<? extends Supplier>> var_144 = buildable.buildBetaNode(var_139, var_140, var_141, var_142, var_143, true);
		final TupleMask var_145 = new TupleMask(new int[] {0, 1}, 2);
		final Stub<Address<? extends Supplier>> var_146 = buildable.buildTrimmer(var_144, var_145);
		buildable.buildConnection(var_146, var_133);
		return var_133;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("secmer.sistar.transform.actorDelFromTropos".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("Actor", 0);
			posMapping.put("Link", 1);

		}
		return posMapping;
	}
}
