/*******************************************************************************
 * Pattern builder for pattern secmer.ontology.asset
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.compiled.emf.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.secmer.ontology;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.compiled.emf.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.compiled.emf.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern secmer.ontology.asset
 */
public class PatternBuilderForasset implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("secmer.ontology.asset".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("secmer.ontology.asset");
		
		final Address<? extends Receiver> var_247 = buildable.patternCollector("secmer.ontology.asset");
		final Stub<Address<? extends Supplier>> var_248 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_249 = EPackage.Registry.INSTANCE.getEPackage("http://securechange.eu/ontology").getEClassifier("Asset");
		final Stub<Address<? extends Supplier>> var_250 = buildable.unaryTypeStub(new FlatTuple(new Object[] {"Asset"}), var_249);
		final TupleMask var_251 = new TupleMask(new int[] {}, 0);
		final TupleMask var_252 = new TupleMask(new int[] {}, 1);
		final TupleMask var_253 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_254 = buildable.buildBetaNode(var_248, var_250, var_251, var_252, var_253, false);
		final TupleMask var_255 = new TupleMask(new int[] {0}, 1);
		final Stub<Address<? extends Supplier>> var_256 = buildable.buildTrimmer(var_254, var_255);
		buildable.buildConnection(var_256, var_247);
		return var_247;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("secmer.ontology.asset".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("Asset", 0);

		}
		return posMapping;
	}
}
