/*******************************************************************************
 * Pattern builder for pattern secmer.ontology.fulfill
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.compiled.emf.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.secmer.ontology;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.compiled.emf.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.compiled.emf.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern secmer.ontology.fulfill
 */
public class PatternBuilderForfulfill implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("secmer.ontology.fulfill".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("secmer.ontology.fulfill");
		
		final Address<? extends Receiver> var_456 = buildable.patternCollector("secmer.ontology.fulfill");
		final Stub<Address<? extends Supplier>> var_457 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_458 = ((EClass) (EPackage.Registry.INSTANCE.getEPackage("http://securechange.eu/ontology").getEClassifier("Fulfils"))).getEStructuralFeature("source");
		final Stub<Address<? extends Supplier>> var_459 = buildable.binaryEdgeTypeStub(new FlatTuple(new Object[] {"Fulfils", "Process"}), var_458);
		final TupleMask var_460 = new TupleMask(new int[] {}, 0);
		final TupleMask var_461 = new TupleMask(new int[] {}, 2);
		final TupleMask var_462 = new TupleMask(new int[] {0, 1}, 2);
		final Stub<Address<? extends Supplier>> var_463 = buildable.buildBetaNode(var_457, var_459, var_460, var_461, var_462, false);
		final Stub<Address<? extends Supplier>> var_464 = buildable.buildInjectivityChecker(var_463, 1, new int[] {0});
		final Object var_465 = ((EClass) (EPackage.Registry.INSTANCE.getEPackage("http://securechange.eu/ontology").getEClassifier("Fulfils"))).getEStructuralFeature("target");
		final Stub<Address<? extends Supplier>> var_466 = buildable.binaryEdgeTypeStub(new FlatTuple(new Object[] {"Fulfils", "Proposition"}), var_465);
		final TupleMask var_467 = new TupleMask(new int[] {0}, 2);
		final TupleMask var_468 = new TupleMask(new int[] {0}, 2);
		final TupleMask var_469 = new TupleMask(new int[] {1}, 2);
		final Stub<Address<? extends Supplier>> var_470 = buildable.buildBetaNode(var_464, var_466, var_467, var_468, var_469, false);
		final Stub<Address<? extends Supplier>> var_471 = buildable.buildInjectivityChecker(var_470, 2, new int[] {0, 1});
		final TupleMask var_472 = new TupleMask(new int[] {1, 2}, 3);
		final Stub<Address<? extends Supplier>> var_473 = buildable.buildTrimmer(var_471, var_472);
		buildable.buildConnection(var_473, var_456);
		return var_456;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("secmer.ontology.fulfill".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("Process", 0);
			posMapping.put("Proposition", 1);

		}
		return posMapping;
	}
}
