/*
* generated by Xtext
*/
package argument.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class ArgumentTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
