/*******************************************************************************
 * EMF Specific pattern signature of the secmer.sistar.wrap.goalName pattern
 * Generated by EMF-IncQuery
 *******************************************************************************/

package signatures.secmer.sistar.wrap;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.viatra2.compiled.emf.runtime.api.IPatternSignature;

/**
 * Domain specific Data transfer Object of the secmer.sistar.wrap.goalName pattern.
 * Class fields correspond to parameters of the pattern. Fields with value null are considered unassigned.
 * Each instance is a partial substitution of pattern parameters, 
 * usable e.g. to represent a match of the pattern.
 */
public class GoalNameSignature implements IPatternSignature {

	//constructor
	public GoalNameSignature(Object Goal, Object Name) {
		this.Goal = Goal;
		this.Name = Name;	
	}

	//private attributes
	private Object Goal;	private Object Name;
	
	//getter methods
	public Object getGoal(){
		 return Goal;
	}

	public Object getName(){
		 return Name;
	}
	
	//setter methods
	public void setGoal(Object Goal){
		 this.Goal=Goal;
	}
	public void setName(Object Name){
		 this.Name=Name;
	}

	//overridden hashCode() and equals() with Tuple-semantics
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		GoalNameSignature other = (GoalNameSignature) obj;
		if (Goal == null) {if (other.Goal != null) return false;}
		else if (!Goal.equals(other.Goal)) return false;
		if (Name == null) {if (other.Name != null) return false;}
		else if (!Name.equals(other.Name)) return false;
		return true;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((Goal == null) ? 0 : Goal.hashCode());
		result = prime * result + ((Name == null) ? 0 : Name.hashCode());
		return result;
	}

	@Override
	public String toString(){
		EStructuralFeature feature = null;
		String _temp = " A(n) goalName signature object ("+hashCode()+")\n";
		// Checks that Goal has a name attribute and uses if it has 
		_temp += "\tGoal = ";
		feature = null;
		if(Goal instanceof EObject)
			feature = ((EObject)Goal).eClass().getEStructuralFeature("name");

		if(feature != null && ((EObject)Goal).eGet(feature) != null) _temp += ((EObject)Goal).eGet(feature).toString();
		else _temp += Goal.toString();
		_temp += "\n";

		// Checks that Name has a name attribute and uses if it has 
		_temp += "\tName = ";
		feature = null;
		if(Name instanceof EObject)
			feature = ((EObject)Name).eClass().getEStructuralFeature("name");

		if(feature != null && ((EObject)Name).eGet(feature) != null) _temp += ((EObject)Name).eGet(feature).toString();
		else _temp += Name.toString();
		_temp += "\n";

		return _temp;
	}

	@Override
	public Object[] toArray() {
		return new Object[] {Goal, Name};
	}
}
