
/*
 * generated by Xtext
 */
 
package uk.ac.open.rbac.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class RBACExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return uk.ac.open.rbac.ui.internal.RBACActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return uk.ac.open.rbac.ui.internal.RBACActivator.getInstance().getInjector("uk.ac.open.rbac.RBAC");
	}
	
}
