<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ontology"
    nsURI="http://securechange.eu/ontology" nsPrefix="ontology">
  <eClassifiers xsi:type="ecore:EClass" name="Situation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="world" eType="#//World"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="World">
    <eStructuralFeatures xsi:type="ecore:EReference" name="goals" upperBound="-1"
        eType="#//Goal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domains" upperBound="-1"
        eType="#//Domain" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" upperBound="-1"
        eType="#//Relationship" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Proposition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityGoal" eSuperTypes="#//Goal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" eSuperTypes="#//Goal"/>
  <eClassifiers xsi:type="ecore:EClass" name="AntiRequirement" eSuperTypes="#//Goal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Domain">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Proposition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//Domain"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//Domain"/>
  <eClassifiers xsi:type="ecore:EClass" name="Asset" eSuperTypes="#//Domain"/>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//Domain"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attacker" eSuperTypes="#//Domain"/>
  <eClassifiers xsi:type="ecore:EClass" name="Proposition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//RelType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//World"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//World"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RelType">
    <eLiterals name="CARRIESOUT" literal="carries out"/>
    <eLiterals name="DELEGATES" value="1" literal="delegates"/>
    <eLiterals name="FULFILS" value="2" literal="fulfils"/>
    <eLiterals name="PROVIDES" value="3" literal="provides"/>
    <eLiterals name="TRUSTS" value="4" literal="trusts"/>
    <eLiterals name="WANTS" value="5" literal="wants"/>
    <eLiterals name="DAMAGES" value="6" literal="damages"/>
    <eLiterals name="ATTACKS" value="7" literal="attacks"/>
    <eLiterals name="ARGUES" value="8" literal="argues"/>
    <eLiterals name="INTERFACES" value="9" literal="interfaces"/>
  </eClassifiers>
</ecore:EPackage>
