<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ontology"
    nsURI="http://securechange.eu/ontology" nsPrefix="ontology">
  <eClassifiers xsi:type="ecore:EClass" name="Situation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="world" eType="#//World"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="World">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" upperBound="-1"
        eType="#//Relationship" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asset" eType="#//Asset"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Proposition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityGoal" eSuperTypes="#//Goal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" eSuperTypes="#//Goal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Domain" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Asset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//Domain"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//Domain"/>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//Domain"/>
  <eClassifiers xsi:type="ecore:EClass" name="Proposition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//RelType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" unique="false"
        upperBound="-1" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Proposition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RelType">
    <eLiterals name="CARRIESOUT" literal="carries out"/>
    <eLiterals name="DEPENDS" value="1" literal="depends"/>
    <eLiterals name="AND_DECOMPOSES" value="2" literal="and decomposes"/>
    <eLiterals name="OR_DECOMPOSES" value="3" literal="or decomposes"/>
    <eLiterals name="HELPS" value="4" literal="+"/>
    <eLiterals name="HURTS" value="5" literal="-"/>
    <eLiterals name="BREAKS" value="6" literal="--"/>
    <eLiterals name="MAKES" value="7" literal="++"/>
    <eLiterals name="DELEGATES" value="8" literal="delegates"/>
    <eLiterals name="FULFILS" value="9" literal="fulfils"/>
    <eLiterals name="PROVIDES" value="10" literal="provides"/>
    <eLiterals name="TRUSTS" value="11" literal="trusts"/>
    <eLiterals name="WANTS" value="12" literal="wants"/>
    <eLiterals name="DAMAGES" value="13" literal="damages"/>
    <eLiterals name="ATTACKS" value="14" literal="attacks"/>
    <eLiterals name="ARGUES" value="15" literal="argues"/>
    <eLiterals name="INTERFACES" value="16" literal="interfaces"/>
    <eLiterals name="CONSUMEs" value="17" literal="consumes"/>
    <eLiterals name="PROTECTS" value="18" literal="protects"/>
  </eClassifiers>
</ecore:EPackage>
