/*
* generated by Xtext
*/
package uk.ac.open.dependency.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class DependencyTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
