/*
* generated by Xtext
*/
package eu.securechange.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class OntologyTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
