/*
* generated by Xtext
*/
package uk.ac.open.problem.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.CharStream;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.common.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.common.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.common.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import uk.ac.open.problem.services.ProblemGrammarAccess;

public class ProblemParser extends AbstractContentAssistParser {
	
	@Inject
	private ProblemGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected uk.ac.open.problem.contentassist.antlr.internal.InternalProblemLexer createLexer(CharStream stream) {
		return new uk.ac.open.problem.contentassist.antlr.internal.InternalProblemLexer(stream);
	}
	
	@Override
	protected uk.ac.open.problem.contentassist.antlr.internal.InternalProblemParser createParser() {
		uk.ac.open.problem.contentassist.antlr.internal.InternalProblemParser result = new uk.ac.open.problem.contentassist.antlr.internal.InternalProblemParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				{
					put(grammarAccess.getProblemDiagramAccess().getAlternatives_1(), "rule__ProblemDiagram__Alternatives_1");
					put(grammarAccess.getNodeAccess().getAlternatives_3_1(), "rule__Node__Alternatives_3_1");
					put(grammarAccess.getModelAccess().getAlternatives_3(), "rule__Model__Alternatives_3");
					put(grammarAccess.getContainerAccess().getAlternatives(), "rule__Container__Alternatives");
					put(grammarAccess.getActorAccess().getAlternatives_2(), "rule__Actor__Alternatives_2");
					put(grammarAccess.getIntentionAccess().getAlternatives(), "rule__Intention__Alternatives");
					put(grammarAccess.getDependableAccess().getAlternatives(), "rule__Dependable__Alternatives");
					put(grammarAccess.getDecompositionAccess().getAlternatives(), "rule__Decomposition__Alternatives");
					put(grammarAccess.getContributionAccess().getAlternatives(), "rule__Contribution__Alternatives");
					put(grammarAccess.getNodeTypeAccess().getAlternatives(), "rule__NodeType__Alternatives");
					put(grammarAccess.getPhenomenonTypeAccess().getAlternatives(), "rule__PhenomenonType__Alternatives");
					put(grammarAccess.getLinkTypeAccess().getAlternatives(), "rule__LinkType__Alternatives");
					put(grammarAccess.getProblemDiagramAccess().getGroup(), "rule__ProblemDiagram__Group__0");
					put(grammarAccess.getProblemDiagramAccess().getGroup_0(), "rule__ProblemDiagram__Group_0__0");
					put(grammarAccess.getNodeAccess().getGroup(), "rule__Node__Group__0");
					put(grammarAccess.getNodeAccess().getGroup_2(), "rule__Node__Group_2__0");
					put(grammarAccess.getNodeAccess().getGroup_3(), "rule__Node__Group_3__0");
					put(grammarAccess.getNodeAccess().getGroup_3_1_1(), "rule__Node__Group_3_1_1__0");
					put(grammarAccess.getNodeAccess().getGroup_3_1_3(), "rule__Node__Group_3_1_3__0");
					put(grammarAccess.getPhenomenonAccess().getGroup(), "rule__Phenomenon__Group__0");
					put(grammarAccess.getPhenomenonAccess().getGroup_2(), "rule__Phenomenon__Group_2__0");
					put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
					put(grammarAccess.getLinkAccess().getGroup_3(), "rule__Link__Group_3__0");
					put(grammarAccess.getLinkAccess().getGroup_3_2(), "rule__Link__Group_3_2__0");
					put(grammarAccess.getLinkAccess().getGroup_4(), "rule__Link__Group_4__0");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getActorAccess().getGroup(), "rule__Actor__Group__0");
					put(grammarAccess.getActorAccess().getGroup_3(), "rule__Actor__Group_3__0");
					put(grammarAccess.getAgentAccess().getGroup(), "rule__Agent__Group__0");
					put(grammarAccess.getAgentAccess().getGroup_2(), "rule__Agent__Group_2__0");
					put(grammarAccess.getRoleAccess().getGroup(), "rule__Role__Group__0");
					put(grammarAccess.getRoleAccess().getGroup_2(), "rule__Role__Group_2__0");
					put(grammarAccess.getPositionAccess().getGroup(), "rule__Position__Group__0");
					put(grammarAccess.getPositionAccess().getGroup_2(), "rule__Position__Group_2__0");
					put(grammarAccess.getGoalAccess().getGroup(), "rule__Goal__Group__0");
					put(grammarAccess.getGoalAccess().getGroup_2(), "rule__Goal__Group_2__0");
					put(grammarAccess.getSoftgoalAccess().getGroup(), "rule__Softgoal__Group__0");
					put(grammarAccess.getTaskAccess().getGroup(), "rule__Task__Group__0");
					put(grammarAccess.getResourceAccess().getGroup(), "rule__Resource__Group__0");
					put(grammarAccess.getBeliefAccess().getGroup(), "rule__Belief__Group__0");
					put(grammarAccess.getAssociationAccess().getGroup(), "rule__Association__Group__0");
					put(grammarAccess.getDependencyAccess().getGroup(), "rule__Dependency__Group__0");
					put(grammarAccess.getAndDecompositionAccess().getGroup(), "rule__AndDecomposition__Group__0");
					put(grammarAccess.getOrDecompositionAccess().getGroup(), "rule__OrDecomposition__Group__0");
					put(grammarAccess.getAndContributionAccess().getGroup(), "rule__AndContribution__Group__0");
					put(grammarAccess.getOrContributionAccess().getGroup(), "rule__OrContribution__Group__0");
					put(grammarAccess.getHelpContributionAccess().getGroup(), "rule__HelpContribution__Group__0");
					put(grammarAccess.getMakeContributionAccess().getGroup(), "rule__MakeContribution__Group__0");
					put(grammarAccess.getHurtContributionAccess().getGroup(), "rule__HurtContribution__Group__0");
					put(grammarAccess.getBreakContributionAccess().getGroup(), "rule__BreakContribution__Group__0");
					put(grammarAccess.getProblemDiagramAccess().getDescriptionAssignment_0_2(), "rule__ProblemDiagram__DescriptionAssignment_0_2");
					put(grammarAccess.getProblemDiagramAccess().getNodesAssignment_1_0(), "rule__ProblemDiagram__NodesAssignment_1_0");
					put(grammarAccess.getProblemDiagramAccess().getLinksAssignment_1_1(), "rule__ProblemDiagram__LinksAssignment_1_1");
					put(grammarAccess.getNodeAccess().getNameAssignment_0(), "rule__Node__NameAssignment_0");
					put(grammarAccess.getNodeAccess().getTypeAssignment_1(), "rule__Node__TypeAssignment_1");
					put(grammarAccess.getNodeAccess().getDescriptionAssignment_2_1(), "rule__Node__DescriptionAssignment_2_1");
					put(grammarAccess.getNodeAccess().getSubproblemAssignment_3_1_0(), "rule__Node__SubproblemAssignment_3_1_0");
					put(grammarAccess.getNodeAccess().getProblemRefAssignment_3_1_1_2(), "rule__Node__ProblemRefAssignment_3_1_1_2");
					put(grammarAccess.getNodeAccess().getIstarAssignment_3_1_2(), "rule__Node__IstarAssignment_3_1_2");
					put(grammarAccess.getNodeAccess().getIstarRefAssignment_3_1_3_2(), "rule__Node__IstarRefAssignment_3_1_3_2");
					put(grammarAccess.getPhenomenonAccess().getTypeAssignment_0(), "rule__Phenomenon__TypeAssignment_0");
					put(grammarAccess.getPhenomenonAccess().getNameAssignment_1(), "rule__Phenomenon__NameAssignment_1");
					put(grammarAccess.getPhenomenonAccess().getDescriptionAssignment_2_1(), "rule__Phenomenon__DescriptionAssignment_2_1");
					put(grammarAccess.getLinkAccess().getFromAssignment_0(), "rule__Link__FromAssignment_0");
					put(grammarAccess.getLinkAccess().getTypeAssignment_1(), "rule__Link__TypeAssignment_1");
					put(grammarAccess.getLinkAccess().getToAssignment_2(), "rule__Link__ToAssignment_2");
					put(grammarAccess.getLinkAccess().getPhenomenaAssignment_3_1(), "rule__Link__PhenomenaAssignment_3_1");
					put(grammarAccess.getLinkAccess().getPhenomenaAssignment_3_2_1(), "rule__Link__PhenomenaAssignment_3_2_1");
					put(grammarAccess.getLinkAccess().getDescriptionAssignment_4_1(), "rule__Link__DescriptionAssignment_4_1");
					put(grammarAccess.getModelAccess().getNameAssignment_1(), "rule__Model__NameAssignment_1");
					put(grammarAccess.getModelAccess().getContainersAssignment_3_0(), "rule__Model__ContainersAssignment_3_0");
					put(grammarAccess.getModelAccess().getIntentionsAssignment_3_1(), "rule__Model__IntentionsAssignment_3_1");
					put(grammarAccess.getModelAccess().getDecompositionsAssignment_3_2(), "rule__Model__DecompositionsAssignment_3_2");
					put(grammarAccess.getModelAccess().getDependenciesAssignment_3_3(), "rule__Model__DependenciesAssignment_3_3");
					put(grammarAccess.getModelAccess().getContributionsAssignment_3_4(), "rule__Model__ContributionsAssignment_3_4");
					put(grammarAccess.getModelAccess().getAssociationsAssignment_3_5(), "rule__Model__AssociationsAssignment_3_5");
					put(grammarAccess.getActorAccess().getNameAssignment_1(), "rule__Actor__NameAssignment_1");
					put(grammarAccess.getActorAccess().getIs_aAssignment_2_0(), "rule__Actor__Is_aAssignment_2_0");
					put(grammarAccess.getActorAccess().getIs_part_ofAssignment_2_1(), "rule__Actor__Is_part_ofAssignment_2_1");
					put(grammarAccess.getActorAccess().getIntentionsAssignment_3_1(), "rule__Actor__IntentionsAssignment_3_1");
					put(grammarAccess.getAgentAccess().getNameAssignment_1(), "rule__Agent__NameAssignment_1");
					put(grammarAccess.getAgentAccess().getIntentionsAssignment_2_1(), "rule__Agent__IntentionsAssignment_2_1");
					put(grammarAccess.getRoleAccess().getNameAssignment_1(), "rule__Role__NameAssignment_1");
					put(grammarAccess.getRoleAccess().getIntentionsAssignment_2_1(), "rule__Role__IntentionsAssignment_2_1");
					put(grammarAccess.getPositionAccess().getNameAssignment_1(), "rule__Position__NameAssignment_1");
					put(grammarAccess.getPositionAccess().getIntentionsAssignment_2_1(), "rule__Position__IntentionsAssignment_2_1");
					put(grammarAccess.getGoalAccess().getNameAssignment_1(), "rule__Goal__NameAssignment_1");
					put(grammarAccess.getGoalAccess().getDecompositionsAssignment_2_1(), "rule__Goal__DecompositionsAssignment_2_1");
					put(grammarAccess.getSoftgoalAccess().getNameAssignment_1(), "rule__Softgoal__NameAssignment_1");
					put(grammarAccess.getTaskAccess().getNameAssignment_1(), "rule__Task__NameAssignment_1");
					put(grammarAccess.getResourceAccess().getNameAssignment_1(), "rule__Resource__NameAssignment_1");
					put(grammarAccess.getBeliefAccess().getNameAssignment_1(), "rule__Belief__NameAssignment_1");
					put(grammarAccess.getAssociationAccess().getSourceAssignment_0(), "rule__Association__SourceAssignment_0");
					put(grammarAccess.getAssociationAccess().getTargetAssignment_2(), "rule__Association__TargetAssignment_2");
					put(grammarAccess.getDependencyAccess().getDependencyFromAssignment_0(), "rule__Dependency__DependencyFromAssignment_0");
					put(grammarAccess.getDependencyAccess().getDependencyToAssignment_2(), "rule__Dependency__DependencyToAssignment_2");
					put(grammarAccess.getAndDecompositionAccess().getTargetAssignment_0(), "rule__AndDecomposition__TargetAssignment_0");
					put(grammarAccess.getAndDecompositionAccess().getSourceAssignment_2(), "rule__AndDecomposition__SourceAssignment_2");
					put(grammarAccess.getOrDecompositionAccess().getTargetAssignment_0(), "rule__OrDecomposition__TargetAssignment_0");
					put(grammarAccess.getOrDecompositionAccess().getSourceAssignment_2(), "rule__OrDecomposition__SourceAssignment_2");
					put(grammarAccess.getAndContributionAccess().getSourceAssignment_0(), "rule__AndContribution__SourceAssignment_0");
					put(grammarAccess.getAndContributionAccess().getTargetAssignment_2(), "rule__AndContribution__TargetAssignment_2");
					put(grammarAccess.getOrContributionAccess().getSourceAssignment_0(), "rule__OrContribution__SourceAssignment_0");
					put(grammarAccess.getOrContributionAccess().getTargetAssignment_2(), "rule__OrContribution__TargetAssignment_2");
					put(grammarAccess.getHelpContributionAccess().getSourceAssignment_0(), "rule__HelpContribution__SourceAssignment_0");
					put(grammarAccess.getHelpContributionAccess().getTargetAssignment_2(), "rule__HelpContribution__TargetAssignment_2");
					put(grammarAccess.getMakeContributionAccess().getSourceAssignment_0(), "rule__MakeContribution__SourceAssignment_0");
					put(grammarAccess.getMakeContributionAccess().getTargetAssignment_2(), "rule__MakeContribution__TargetAssignment_2");
					put(grammarAccess.getHurtContributionAccess().getSourceAssignment_0(), "rule__HurtContribution__SourceAssignment_0");
					put(grammarAccess.getHurtContributionAccess().getTargetAssignment_2(), "rule__HurtContribution__TargetAssignment_2");
					put(grammarAccess.getBreakContributionAccess().getSourceAssignment_0(), "rule__BreakContribution__SourceAssignment_0");
					put(grammarAccess.getBreakContributionAccess().getTargetAssignment_2(), "rule__BreakContribution__TargetAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			uk.ac.open.problem.contentassist.antlr.internal.InternalProblemParser typedParser = (uk.ac.open.problem.contentassist.antlr.internal.InternalProblemParser) parser;
			typedParser.entryRuleProblemDiagram();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ProblemGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ProblemGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
