/*******************************************************************************
 * Pattern builder for pattern secmer.sistar.wrap.decomposeDirectAND
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.compiled.emf.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.secmer.sistar.wrap;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.compiled.emf.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.compiled.emf.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern secmer.sistar.wrap.decomposeDirectAND
 */
public class PatternBuilderFordecomposeDirectAND implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("secmer.sistar.wrap.decomposeDirectAND".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("secmer.sistar.wrap.decomposeDirectAND");
		
		final Address<? extends Receiver> var_319 = buildable.patternCollector("secmer.sistar.wrap.decomposeDirectAND");
		final Stub<Address<? extends Supplier>> var_320 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Stub<Address<? extends Supplier>> var_321 = buildable.patternCallStub(new FlatTuple(new Object[] {"Parent", "Child", "CompositionType"}), "secmer.sistar.wrap.decomposeDirectWithType");
		final TupleMask var_322 = new TupleMask(new int[] {}, 0);
		final TupleMask var_323 = new TupleMask(new int[] {}, 3);
		final TupleMask var_324 = new TupleMask(new int[] {0, 1, 2}, 3);
		final Stub<Address<? extends Supplier>> var_325 = buildable.buildBetaNode(var_320, var_321, var_322, var_323, var_324, false);
		final AbstractEvaluator var_326 = new AbstractEvaluator(){ 
			@Override 
			public Object doEvaluate(Tuple tuple) throws Exception { 
				return VPMTermEvaluator.equals(tuple.get(2).toString(),"AND");
			}
		};
		final Stub<Address<? extends Supplier>> var_327 = buildable.buildPredicateChecker(var_326, null, new int[] {2}, var_325);
		final TupleMask var_328 = new TupleMask(new int[] {0, 1}, 3);
		final Stub<Address<? extends Supplier>> var_329 = buildable.buildTrimmer(var_327, var_328);
		buildable.buildConnection(var_329, var_319);
		return var_319;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("secmer.sistar.wrap.decomposeDirectAND".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("Parent", 0);
			posMapping.put("Child", 1);

		}
		return posMapping;
	}
}
