<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="customStyle"
    nsURI="http://www.custom-style.org" nsPrefix="cust">
  <eClassifiers xsi:type="ecore:EClass" name="ActorStyle" eSuperTypes="../../../plugin/org.eclipse.gmf.runtime.notation/model/notation.ecore#//Style">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actorWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actorHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actorX" eType="ecore:EDataType ../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actorY" eType="ecore:EDataType ../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rationaleShape" eType="#//EShapeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EShapeType">
    <eLiterals name="OVAL"/>
    <eLiterals name="RECTANGLE" value="1" literal="RECTANGLE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreLocation" eSuperTypes="../../../plugin/org.eclipse.gmf.runtime.notation/model/notation.ecore#//Style">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coreWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coreHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coreX" eType="ecore:EDataType ../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coreY" eType="ecore:EDataType ../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectorDecoration" eSuperTypes="../../../plugin/org.eclipse.gmf.runtime.notation/model/notation.ecore#//Style">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decorationSource" eType="#//EEndDecorationType"
        defaultValueLiteral="NONE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decorationMiddle" eType="#//EMidDecorationType"
        defaultValueLiteral="NONE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decorationTarget" eType="#//EEndDecorationType"
        defaultValueLiteral="NONE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decorationMiddleText" eType="ecore:EDataType ../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectionLineStyle" eType="#//EConnectionLineStyle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textSource" eType="ecore:EDataType ../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textMiddle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textTarget" eType="ecore:EDataType ../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EEndDecorationType">
    <eLiterals name="NONE"/>
    <eLiterals name="SOLID_ARROW" value="1"/>
    <eLiterals name="LINE_ARROW" value="2"/>
    <eLiterals name="BOX" value="3" literal="BOX"/>
    <eLiterals name="SOLID_ARROW_FILL" value="4"/>
    <eLiterals name="BOX_FILL" value="5"/>
    <eLiterals name="DIAMOND" value="6"/>
    <eLiterals name="DIAMOND_FILL" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EMidDecorationType">
    <eLiterals name="NONE"/>
    <eLiterals name="ARROW" value="1"/>
    <eLiterals name="BOX" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EConnectionLineStyle">
    <eLiterals name="SOLID"/>
    <eLiterals name="DASHED" value="1"/>
    <eLiterals name="DOTTED" value="2"/>
  </eClassifiers>
</ecore:EPackage>
