<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="situation"
    nsURI="http://securechange.eu/situation" nsPrefix="situation">
  <eClassifiers xsi:type="ecore:EClass" name="Situation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="things" upperBound="-1"
        eType="#//Thing" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Thing"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//Thing">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EntityType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship" eSuperTypes="#//Thing">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//RelationshipType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Thing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Thing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Domain" eSuperTypes="#//Thing">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DomainType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Entity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EntityType">
    <eLiterals name="DomainAssumption" literal="DA"/>
    <eLiterals name="Function" value="1" literal="FR"/>
    <eLiterals name="Security" value="2" literal="SR"/>
    <eLiterals name="Anti" value="3" literal="AR"/>
    <eLiterals name="QualityProposition" value="4" literal="Q"/>
    <eLiterals name="Argument" value="5" literal="A"/>
    <eLiterals name="Actor" value="6" literal="actor"/>
    <eLiterals name="Action" value="7" literal="action"/>
    <eLiterals name="Attacker" value="8" literal="attacker"/>
    <eLiterals name="Process" value="9" literal="process"/>
    <eLiterals name="Activity" value="10" literal="activity"/>
    <eLiterals name="Resource" value="11" literal="resource"/>
    <eLiterals name="Asset" value="12" literal="asset"/>
    <eLiterals name="Event" value="13" literal="event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DomainType">
    <eLiterals name="Machine" literal="M"/>
    <eLiterals name="Requirement" value="1" literal="R"/>
    <eLiterals name="Specification" value="2" literal="S"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RelationshipType">
    <eLiterals name="Wants" literal="wants"/>
    <eLiterals name="Does" value="1" literal="does"/>
    <eLiterals name="AND" value="2" literal="and"/>
    <eLiterals name="OR" value="3" literal="or"/>
    <eLiterals name="TRUST" value="4" literal="trusts"/>
    <eLiterals name="DELEGATE" value="5" literal="delegates"/>
    <eLiterals name="HURT" value="6" literal="-"/>
    <eLiterals name="HELP" value="7" literal="+"/>
    <eLiterals name="BREAK" value="8" literal="--"/>
    <eLiterals name="MAKE" value="9" literal="++"/>
    <eLiterals name="Fulfils" value="10" literal="fulfils"/>
    <eLiterals name="Provides" value="11" literal="provides"/>
    <eLiterals name="Consumes" value="12" literal="consumes"/>
    <eLiterals name="Exploits" value="13" literal="exploits"/>
    <eLiterals name="Damages" value="14" literal="damages"/>
    <eLiterals name="Attacks" value="15" literal="attacks"/>
    <eLiterals name="Argues" value="16" literal="argues"/>
  </eClassifiers>
</ecore:EPackage>
