/*
 * generated by Xtext
 */
package uk.ac.open.dependency.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DependencyUiModule extends uk.ac.open.dependency.ui.AbstractDependencyUiModule {
	public DependencyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
