grammar uk.ac.open.dependency.Dependency with org.eclipse.xtext.common.Terminals

generate dependency "http://www.Dependency"

Model: ('graph' name=ID)?
	(nodes+=Node | dependencies+=Dependency)*;

Node:
	name=ID ('{' ('see' referrence+=STRING)* '}')?;

Dependency: Coupling | Precedence;

Coupling:
	from=[Node] '--' to=[Node];
	
Precedence:
	from=[Node] '->' to=[Node];
	
terminal ID: ('#' (!('#'))+ '#') |
  ('^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*);
	