<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eventcalculus"
    nsURI="http://www.ac.uk/open/EventCalculus" nsPrefix="eventcalculus">
  <eClassifiers xsi:type="ecore:EClass" name="Knowledge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//Rule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vars" upperBound="-1" eType="#//Var"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="decl" eType="#//VarDecl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//BoolExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vars" unique="false" upperBound="-1"
        eType="#//Var"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntTerm" eSuperTypes="#//IntExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="const" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="#//Var"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryIntExpr" eSuperTypes="#//IntExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="opr" upperBound="-1" eType="#//IntTerm"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binaryop" eType="#//BinaryIntOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryIntOp">
    <eLiterals name="PLUS" literal="+"/>
    <eLiterals name="MINUS" value="1" literal="-"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemporalPredicate" eSuperTypes="#//BoolExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="args" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="time" eType="#//IntExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoolExpr"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryBoolExpr" eSuperTypes="#//BoolExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unaryop_lhs" eType="#//UnaryBoolOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opr" upperBound="-1" eType="#//BoolExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ops" upperBound="-1" eType="#//BoolExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnaryBoolOp">
    <eLiterals name="NEGATION" literal="!"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryBoolExpr" eSuperTypes="#//BoolExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="opr" upperBound="-1" eType="#//BoolExpr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binaryop" eType="#//BinaryBoolOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryBoolOp">
    <eLiterals name="IMPLICATION" literal="->"/>
    <eLiterals name="EQUIVALENCE" value="1" literal="&lt;->"/>
    <eLiterals name="AND" value="2" literal="&amp;"/>
    <eLiterals name="OR" value="3" literal="|"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sort" eSuperTypes="#//Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="#//Path" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Var">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fluent" eSuperTypes="#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//Term" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//Term" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="args" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HoldsAt" eSuperTypes="#//TemporalPredicate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fluent" eType="#//Term"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Happens" eSuperTypes="#//TemporalPredicate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//Term"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Initiates" eSuperTypes="#//TemporalPredicate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//Term"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fluent" eType="#//Term"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="args2" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Terminates" eSuperTypes="#//TemporalPredicate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//Term"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fluent" eType="#//Term"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="args2" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Path">
    <eStructuralFeatures xsi:type="ecore:EReference" name="files" upperBound="-1"
        eType="#//File" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="File">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="names" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
